### ISSUE TITLE
AWS RDS 구축

### ISSUE THREAD

**Issue by gminiy** [codesquad-project-team/backend#17]
**Is your feature request related to a problem? Please describe.**
DB 서버 구축합시다
**Describe the solution you'd like**
EC2에 mysql 만들어서 사용할수도 있지만 RDS가 어차피 무료라서 RDS 만들어서 사용하는게 좋을듯?

**Describe alternatives you've considered**

**Additional context**

**Comment by Min-92** [comment]
RDS무료아니구 사용하는만큼 내는걸로 알고있어요오

**Comment by gminiy** [comment]
웅웅 프리티어로 20기가 1년 사용가능해서 생성완료했습니다앙~
