### ISSUE TITLE
Database ER(Entity Relationship) 작성

### ISSUE THREAD

**Issue by Min-92** [codesquad-project-team/backend#3]
**Is your feature request related to a problem? Please describe.**\
DB 테이블 설계를 위한 ER 작성

**Describe the solution you'd like**
MySql workbench 를 이용한 ER작성

**Describe alternatives you've considered**

**Additional context**

**Comment by Min-92** [comment]
![image](https://user-images.githubusercontent.com/26920620/65751017-a132d680-e144-11e9-9a48-3583817c8f1c.png)

**Comment by gminiy** [comment]
좌표의 data type 을 DEC(10, 6)으로 변경해야할듯. 10진수 소숫점 6자리까지 사용한다는 뜻

**Comment by gminiy** [comment]
Description data type을 BLOB나 TEXT로 바꾸는게 좋을까요 아니면 VARCHAR(255)정도로 하는게 좋을까요.
VARCHAR 최대 크기가 255임. BLOB는 255 byte이상일때 사용하는데 남발하면 너무 낭비긴 한데.... 한글로 쓰면 255바이트면 120자정도 쓸 수 있거든요. 너무 적나?

**Comment by Min-92** [comment]
* 위도 값의 범위 : +90.000000(North)북위 90도 ~ -90.000000(South)남위 90도
* 경도 값의 범위 : +180.000000(East)동경 180도 ~ -180.000000(West)서경 180도 [그리니치 천문대 기준 0도]
라고 하네요
DEC(3, 7)로 해도 될것같습니당

**Comment by Min-92** [comment]
Description data type 은 BLOB으로 하고 글자수 제한 두는걸로 하겠습니다~
ex ) 인스타 2200자 제한 2402byte

**Comment by andole87** [comment]
`url` `varchar(64)` 도 한번 고려해주세요~

**Comment by Min-92** [comment]
image.url VARCHAR(64) -> VARCHAR(255)로 수정하겠습니다~
