### ISSUE TITLE
dummy data 생성 환경 만들기

### ISSUE THREAD

**Issue by gminiy** [codesquad-project-team/backend#7]
**Is your feature request related to a problem? Please describe.**
Test 환경을 만들기 위해서 dummy data 가 필요함.

**Describe the solution you'd like**
sequelize-cli migration 을 이용해서 만들 수 있을 듯?
프론트에서 db 설치 없이 server를 이용할 수 있게 하기 위해서는 우선 배포를 빨리 해야하나?
아니면 초기 셋팅 환경에 dummy db, fake db를 사용할 수 있게 만들어야하나?

**Describe alternatives you've considered**

**Additional context**

**Comment by Min-92** [comment]
demo images

![man](https://user-images.githubusercontent.com/26920620/66458920-e47b3680-eaae-11e9-80c0-59396fce37c2.png)
![image](https://user-images.githubusercontent.com/26920620/66458974-02489b80-eaaf-11e9-95c9-f9e72e7f15f4.png)

**Comment by gminiy** [comment]
sequelize-cli seed 기능을 사용해서 user, post, location, image table의 dummy data 생성하는 환경 구축했습니다.
